MyAccountBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from app.views import dashboard, contacts, base, invoice, collections, \
    products, inventory, common_views, bundle_pack


# Authorization
urlpatterns = [
    path('', dashboard.index, name = 'home'),
    path('login/', auth_views.LoginView.as_view(template_name = 'app/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'app/registration/logout.html'), name = 'logout'),
    re_path(r'^accounts/*', RedirectView.as_view(pattern_name='login', permanent=True)),
    path('unauthorized/', login_required(base.UnAuthorized.as_view()), name = 'unauthorized'),
]

# Dashboard
urlpatterns += [
    path('dashboard/', never_cache(login_required(dashboard.Dashboard.as_view())), name = 'dashboard'),
]

# Contacts
urlpatterns += [
    path('contacts/', never_cache(login_required(contacts.ContactsView.as_view())), name = 'contacts'),
    path('contacts/add/', never_cache(login_required(contacts.add_contacts)), name = 'add-contacts'),
    path('contacts/add_address/', never_cache(login_required(contacts.add_address_details_form)), name = 'add_address_details_form'),
    path('contacts/add_accounts/', never_cache(login_required(contacts.add_accounts_details_form)), name = 'add_accounts_details_form'),
    path('contacts/edit/<int:ins>/', never_cache(login_required(contacts.edit_contact)), name = 'edit-contact'),
    
    path('contacts/check_appid/', never_cache(login_required(contacts.check_app_id)), name='check-appid'),
    path('contacts/user_exists_in_list/', never_cache(login_required(contacts.user_exists_in_list)), name='check-appid-user-exist'),
    path('contacts/upload/', never_cache(login_required(contacts.ContactsFileUploadView.as_view())), name='contacts-upload'),
    path('contacts/status_change/<slug:slug>/<int:ins>/', never_cache(login_required(contacts.status_change)), name='contact-status-change'),
    path('contacts/delete/<int:ins>/', never_cache(login_required(contacts.delete_contact)), name='contact-delete'),

    path('contacts/edit_contact_details_form/', never_cache(login_required(contacts.edit_contact_details_form)), name = 'edit_contact_details_form'),
    path('contacts/edit_tax_details_form/', never_cache(login_required(contacts.edit_tax_details_form)), name = 'edit_tax_details_form'),
    path('contacts/edit_other_details_form/', never_cache(login_required(contacts.edit_other_details_form)), name = 'edit_other_details_form'),
    path('contacts/edit_address_details_form/', never_cache(login_required(contacts.edit_address_details_form)), name = 'edit_address_details_form'),
    path('contacts/edit_accounts_details_form/', never_cache(login_required(contacts.edit_accounts_details_form)), name = 'edit_accounts_details_form'),
    path('contacts/edit_social_details_form/', never_cache(login_required(contacts.edit_social_details_form)), name = 'edit_social_details_form'),

    path('contacts/delete_address/<int:ins>/', never_cache(login_required(contacts.delete_contact_address)), name = 'delete_contact_address'),
    path('contacts/delete_accounts/<int:ins>/', never_cache(login_required(contacts.delete_accounts_details)), name = 'delete_accounts_details'),

]

# Invoice
urlpatterns += [
    path('invoice/', never_cache(login_required(invoice.Invoice.as_view())), name = 'invoice'),
    path('invoice/invoice_designer/', never_cache(login_required(invoice.InvoiceDesigner.as_view())), name = 'invoice-designer'),
    path('invoice/invoice_designer/manage/', never_cache(login_required(invoice.manage_invoice_designs)), name = 'manage-invoice-designs'),
    path('invoice/create_invoice/', never_cache(login_required(invoice.CreateInvoice.as_view())), name = 'create-invoice'),
    path('invoice/view_invoice/<int:ins>/', never_cache(login_required(invoice.ViewInvoice.as_view())), name = 'view-invoice'),
    path('invoice/create_invoice/contacts/<int:ins>/', never_cache(login_required(invoice.CreateContactInvoice.as_view())), name = 'create-contact-invoice'),
    path('invoice/create_invoice/collections/<int:ins>/', never_cache(login_required(invoice.CreateCollectionInvoice.as_view())), name = 'create-collection-invoice'),
]

urlpatterns +=[
    path('invoice/get_pdf/<int:ins>/', never_cache(login_required(invoice.get_pdf)), name = 'get_pdf'),
    
] 

# Collections
urlpatterns += [
    path('collections/', never_cache(login_required(collections.view_collections)), name = 'collections'),
    path('collections/contact/<int:ins>/', never_cache(login_required(collections.view_contact_collections)), name = 'contact-collections'),
    path('collections/add_collections/', never_cache(login_required(collections.AddCollections.as_view())), name = 'add-collections'),
    path('collections/add_collections/partial/<int:ins>/', never_cache(login_required(collections.AddPartialCollection.as_view())), name = 'add-partial-collections'),
    path('collections/edit/<int:ins>/', never_cache(login_required(collections.Edit_Collection.as_view())), name = 'edit_collections'),
    path('collections/edit_partial/<int:ins>/<int:obj>/', never_cache(login_required(collections.Edit_PartialCollection.as_view())), name = 'edit_partial_collection'),
]

# Products
urlpatterns += [
    path('products/', never_cache(login_required(products.view_products)), name = 'view_products'),
    path('products/add/', never_cache(login_required(products.AddProducts.as_view())), name = 'add_products'),
    path('products/edit/<int:ins>/', never_cache(login_required(products.EditProducts.as_view())), name = 'edit_product'),
    path('products/delete/<int:ins>/', never_cache(login_required(products.delete_product)), name='product-delete'),
    path('products/clone/<int:ins>/', never_cache(login_required(products.clone_product)), name='product-clone'),
    path('products/status_change/<slug:slug>/<int:ins>/', never_cache(login_required(products.status_change)), name='product-status-change'),
]

# Product Bundle
urlpatterns +=[
    path('products/bundle/view/', never_cache(login_required(bundle_pack.ProductBundelView.as_view())), name = 'view_product_bundles'),
]



# Inventory
urlpatterns += [
    path('inventory/', never_cache(login_required(inventory.view_inventory)), name = 'view_inventory'),
    path('inventory/add/', never_cache(login_required(inventory.AddInventory.as_view())), name = 'add_inventory'),
    path('inventory/products/<int:ins>/', never_cache(login_required(inventory.InventoryProducts.as_view())), name = 'view_inventory_products'),
    path('inventory/products/delete/<int:ins>/', never_cache(login_required(inventory.delete_inventory_product)), name = 'delete_inventory_product'),
    path('inventory/get_edit_inventory_product_form/', never_cache(login_required(inventory.get_edit_inventory_product_form)), name = 'get_edit_inventory_product_form'),
    path('inventory/edit_inventory_product/', never_cache(login_required(inventory.edit_inventory_product)), name = 'edit_inventory_product'),
]

# AJAX
urlpatterns += [
    path('fetch_contact_addresses/<int:ins>/', never_cache(login_required(common_views.fetch_contact_addresses)), name='fetch_contact_addresses'),
    path('fetch_product_details/<int:ins>/', never_cache(login_required(common_views.fetch_product_details)), name='fetch_product_details'),
    path('ajax_add_product/', never_cache(login_required(products.ajax_add_product)), name='ajax_add_product'),
    path('fetch_products_dropdown/', never_cache(login_required(common_views.fetch_products_dropdown)), name='fetch_products_dropdown'),
    path('add_contact_or_employee/', never_cache(login_required(common_views.add_contact_or_employee)), name='add_contact_or_employee'),
    path('get_contacts_dropdown/', never_cache(login_required(common_views.get_contacts_dropdown)), name='get_contacts_dropdown'),
    path('add_edit_address/<int:ins>/', never_cache(login_required(common_views.add_edit_address)), name='add_edit_address'),
    path('add_edit_address/<int:ins>/<int:obj>/', never_cache(login_required(common_views.add_edit_address)), name='add_edit_address'),
]





#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

app/models/contacts_model.py
from django.db import models
from django.contrib.auth.models import User
from app.other_constants import *
from django.db.models.signals import post_save
from django.dispatch import receiver

from uuid import uuid4
import os

#==========================================================================
#   CHANGE CSV IMPORT FILE NAMES
#==========================================================================
#
def file_rename(instance, filename):

    upload_path = 'contact_csv_imports'
    ext = filename.split('.')[-1]
    return  os.path.join(upload_path,'{}.{}'.format(uuid4().hex, ext))


#==========================================================================
#   CHANGE CSV IMPORT FILE NAMES
#==========================================================================
#
def attachments_rename(instance, filename):

    upload_path = 'contact_attachments'
    ext = filename.split('.')[-1]
    return  os.path.join(upload_path,'{}.{}'.format(uuid4().hex, ext))



#**************************************************************************
#   CONTACT'S DATA
#**************************************************************************
class Contacts(models.Model):

    user = models.ForeignKey(User, on_delete = models.CASCADE, db_index = True, null = True,)

    app_id = models.CharField(
        max_length = 30,
        db_index = True,
        blank = True,
        null = True,
    )

    is_imported_user = models.BooleanField(
        default = False,
        db_index = True,
        choices = user_constants.IS_TRUE,
        blank = True,
    )

    imported_user = models.ForeignKey(
        User,
        related_name = 'imported_user',
        db_index = True,
        blank = True,
        null = True,
        on_delete = models.SET_NULL,
    )

    customer_type = models.IntegerField(
        db_index = True,
        choices = user_constants.CUSTOMER_TYPE,
        default = 1,
        null = True,
        blank = True,
    )

    is_sub_customer = models.IntegerField(
        choices = user_constants.IS_SUB_CUSTOMER,
        default = 1,
        db_index = True,
        null = True,
        blank = True,
    )

    salutation = models.IntegerField(
        db_index = True,
        default = 0,
        choices = user_constants.SALUTATIONS,
    )

    contact_name = models.CharField(
        max_length = 250,
        blank = False,
        null = False,
        db_index = True,
    )

    display_name = models.CharField(
        max_length = 250,
        blank = True,
        null = True,
        db_index = True,
    )

    organization_type = models.IntegerField(
        db_index = True,
        choices = user_constants.ORGANIZATION_TYPE,
        default = 1,
    )

    organization_name = models.CharField(
        max_length = 250,
        db_index = True,
        blank = True,
        null = True,
    )

    is_msme_reg = models.BooleanField(
        db_index = True,
        choices = user_constants.IS_TRUE,
        default = False,
    )

    email = models.EmailField(
        blank = True, 
        null = True, 
        db_index = True,
    )

    phone = models.CharField(
        max_length = 250,
        db_index = True,
        blank = True,
        null = True,
    )

    website = models.CharField(
        max_length = 250,
        db_index = True,
        blank = True,
        null = True,
    )

    facebook = models.CharField(
        blank = True,
        null = True,
        max_length = 250,
    )

    twitter = models.CharField(
        blank = True,
        null = True,
        max_length = 250,
    )

    is_active = models.BooleanField(
        db_index = True,
        choices =  user_constants.IS_TRUE,
        default = True,
    )    

    notes = models.TextField(
        blank = True,
        null = True,
    )

    attachements = models.FileField(
        upload_to = attachments_rename,
        db_index = True,
        blank = True,
        null = True,
    )
    
    created_on = models.DateTimeField(
        auto_now = True,
        db_index = True,
    ) 

    updated_on = models.DateTimeField(
        auto_now = False,
        db_index = True,
        null = True,
    )
    
    def __str__(self):
        return self.contact_name.upper()

    def is_active_value(self):
        if self.is_active:
            return "YES"
        return "NO"  

    class Meta:
        verbose_name_plural = 'contacts_tbl'

#===================================================================================
# CONTACTS FILE UPLOAD 
#===================================================================================

class ContactsFileUpload(models.Model):

    user = models.ForeignKey(
        User,
        db_index = True,
        blank = True,
        null = True,
        on_delete = models.CASCADE,
    )

    csv_file = models.FileField(
        upload_to = file_rename,
        db_index = True,
        blank = True,
        null = True,
    )

    created_date = models.DateTimeField(
        auto_now_add = True,
        auto_now = False,
        db_index = True,
    )

    class Meta:
        verbose_name_plural = 'contacts_fileupload_tbl'
    

app/views/base.py
from django.views import View
from django.shortcuts import render


class UnAuthorized(View):

    def get(self, request):
        template_name = 'app/base/error_page.html'
        return render(request, template_name, {})

app/templates/app/app_files/contacts/base.html
{% extends 'app/base/base.html' %}
{% load static %}

{% load common_filters %}
{% load pagination %}

{% block content %}
<div class="row custom-row" style="padding:10px; background: linear-gradient(60deg,#f5700c,#ff9800);">
    <ul style="list-style:none; margin:0px; color:#FFFFFF; padding:0px;">        
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'contacts' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="View Contacts As List">
                <i class="material-icons">list</i>
            </a>
        </li>
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'add-contacts' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Add Contact">
                <i class="material-icons">add_to_queue</i>
            </a>
        </li>
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'contacts-upload' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Upload Contacts">
                <i class="material-icons">cloud_upload</i>
            </a>            
        </li>
    </ul>
</div>


<div class="container">
    {% include included_template %}
</div>

{% endblock %}

app/templates/app/app_files/contacts/index.html
{% extends 'app/base/base.html' %}
{% load static %}

{% load common_filters %}
{% load pagination %}

{% block content %}

<div class="row custom-row" style="padding:10px; background: linear-gradient(60deg,#f5700c,#ff9800);">
    <ul style="list-style:none; margin:0px; color:#FFFFFF; padding:0px;">        
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'contacts' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="View Contacts As List">
                <i class="material-icons">list</i>
            </a>
        </li>
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'add-contacts' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Add Contact">
                <i class="material-icons">add_to_queue</i>
            </a>
        </li>
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'contacts-upload' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Upload Contacts">
                <i class="material-icons">cloud_upload</i>
            </a>            
        </li>
    </ul>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">View Contacts</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" width="100%" cellspacing="0">
                        <thead class="text-primary">
                            <th>Sl. No.</th>
                            <th>Contact Name</th>
                            <th>User APP-ID</th>
                            <th>Customer Type</th>
                            <th>Is Sub Customer</th>
                            <th>Active</th>
                            <th>Organisation Type</th>
                            <th>Organisation Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Website</th>                
                            <th>Action</th>                
                        </thead>
                        <tbody>
                            {% for contact in contacts %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{contact.display_name}}</td>
                                    <td>{{contact.app_id}}</td>
                                    <td>{{contact.get_customer_type_display|upper}}</td>
                                    <td>{{contact.get_is_sub_customer_display|upper}}</td>
                                    <td class="text-center">
                                        {% if contact.is_active %}
                                            <i class="material-icons">check</i>
                                        {% else %}
                                            <i class="material-icons">clear</i>
                                        {% endif %}
                                    </td>
                                    <td>{{contact.get_organization_type_display|upper}}</td>
                                    <td>{{contact.organization_name|upper}}</td>
                                    <td>{{contact.email}}</td>
                                    <td>{{contact.phone}}</td>
                                    <td>{{contact.website}}</td>                        
                                    <td class="text-center">
                                        <a href="{% url 'add-contacts' 'step1' contact.id %}" class="btn btn-primary btn-sm" style="padding:5px 5px;">
                                            <i class="material-icons">create</i>
                                        </a>
                                        <a href="{% url 'contact-collections' contact.id %}" class="btn btn-warning btn-sm" style="padding:5px 5px;">
                                            <i class="material-icons">attach_money</i>
                                        </a>
                                        {% if contact.is_active %}
                                            <a href="{% url 'status-change' 'deactivate' contact.id %}" class="btn btn-sm btn-default" title="deactivate" style="padding:5px 5px;">
                                                <i class="material-icons">clear</i>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'status-change' 'activate' contact.id %}" class="btn btn-sm btn-success" title="deactivate" style="padding:5px 5px;">
                                                <i class="material-icons">check</i>
                                            </a>
                                        {% endif %}
                                        <a href="{% url 'contacts-delete' contact.id %}" class="btn btn-danger btn-sm" style="padding:5px 5px;">
                                            <i class="material-icons">delete_forever</i>
                                        </a>
                                    </td>   
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>    
                </div>
            </div>
        </div>    
    </div>     
</div>


{% endblock %}

app/templates/app/app_files/contacts/upload_contacts.html
<style>
p{
    margin-bottom:0px;
    line-height:20px;
}
</style>

<div class="row">
    <div class="col-lg-12" style="padding:0px">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">Import Contacts</h4>
                <p class="card-category"><strong>Upload CSV</strong></p>
            </div>  
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}

                    {% if error %}
                        <div class="alert alert-danger">
                            {{ error|safe }}
                        </div>
                    {% endif %}

                    <div class="table" style="padding:10px 0px;">
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:0px 10px;">
                                <label>Upload CSV</label>
                            </div>
                            <div class="d-table-cell" style="padding:5px 10px;">
                                {{ upload_form.csv_file }}                                
                            </div>
                            <div class="d-table-cell" style="padding:0px;">
                                <button class="btn btn-success" style="vertical-align: inherit;">Upload</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- 
    DOCUMENTATION FOR CSV
-->

<div class="row">
    <div class="col-lg-12" style="padding:0px">
        <div class="card">
            <div class="card-header card-header-info">
                <h4 class="card-title ">CSV DOCUMENTATION FOR IMPORTING CONTACTS</h4>
                <p class="card-category"><strong>Please fllow the documentation</p>
            </div> 
            <div class="card-body">
                <div class="table table-responsive">
                    <table class="table table-bordered" style="background-color:#FFFFFF">
                        <tr class="bg-info" style="font-weight:bold">
                            <td class="text-center" width="200px" style="font-size:110%; padding:10px; color:#000000 !important;">Column Header</td>
                            <td class="text-center" style="font-size:110%; padding:10px; color:#000000 !important;">Column Value</td>
                            <td class="text-center" style="font-size:110%; padding:10px; color:#000000 !important;">Datatype</td>
                            <td class="text-center" style="font-size:110%; padding:10px; color:#000000 !important;">Optional</td>
                            <td class="text-center" width="400px" style="font-size:110%; padding:10px; color:#000000 !important;">Description</td>
                        </tr>
                        {% for i,j in documentation_dict.items %}
                        <tr style="background-color: #000000; color:#FFFFFF; ">
                            <td colspan="5" style="font-size:110%; padding:10px;"><strong>{{i}}</strong></td>
                        </tr>
                            {% for x,v in j.items %}
                                <tr>
                                    <td style="font-size:110%"><strong>{{x}}</strong></td>
                                    <td>{{v.value|safe}}</td>
                                    <td style="font-size:110%"><strong>{{v.datatype}}</strong></td>
                                    <td class="text-center">{{v.optional|safe}}</td>
                                    <td>{{v.description|safe}}</td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/app/app_files/contacts/view_contacts.html
<style>

</style>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">View Contacts</h4>                
            </div>
            <div class="card-body">
                <form method="get">
                    <div class="input-group pull-right" style="width:400px; margin-bottom:10px;">
                
                        <input name="search" type="text" class="form-control" placeholder="Search" style="height: 41px !important">
                        <div class="input-group-append">
                            <button class="btn btn-sm btn-success" type="submit()" style="border-radius:0px;">
                                <i class="material-icons">search</i> <span style="font-size:14px;">Search</span>
                            </button>
                        </div>
                    </div>
                </form>
                <div class="table">
                    <table class="table-responsive table-bordered" width="100%" cellspacing="0">
                        <thead  style="background-color: #EEEEEE; color:#000000; font-size:11px">
                            <th class="text-center" style="color:#000000; font-size:11px">SL. No.</th>
                            <th class="text-center" style="color:#000000; font-size:11px">UID</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Contact Name</th>
                            <th class="text-center" style="color:#000000; font-size:11px">User APP-ID</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Customer Type</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Is Sub Customer</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Active</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Organisation Type</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Organisation Name</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Email</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Phone</th>
                            <th class="text-center" style="color:#000000; font-size:11px">Website</th>                
                            <th class="text-center" style="color:#000000; font-size:11px;">Action</th>                
                        </thead>
                        <tbody>
                            {% for contact in contacts %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>CT-0000{{contact.id}}</td>
                                    <td>{{contact.display_name}}</td>
                                    <td>{{contact.app_id}}</td>
                                    <td>{{contact.get_customer_type_display|upper}}</td>
                                    <td>{{contact.get_is_sub_customer_display|upper}}</td>
                                    <td class="text-center">
                                        {% if contact.is_active %}
                                            <i class="material-icons">check</i>
                                        {% else %}
                                            <i class="material-icons">clear</i>
                                        {% endif %}
                                    </td>
                                    <td>{{contact.get_organization_type_display|upper}}</td>
                                    <td>{{contact.organization_name|upper}}</td>
                                    <td>{{contact.email}}</td>
                                    <td>{{contact.phone}}</td>
                                    <td>{{contact.website}}</td>                        
                                    <td class="text-center">
                                        <a title="Edit Contact" href="{% url 'edit-contact' contact.id %}" class="btn btn-primary btn-sm" style="padding:5px 5px;">
                                            <i class="material-icons">create</i>
                                        </a>
                                        {% if contact.is_active %}
                                            <a title="Deactivate Contact" href="{% url 'contact-status-change' 'deactivate' contact.id %}" class="btn btn-sm btn-default" style="padding:5px 5px;">
                                                <i class="material-icons">clear</i>
                                            </a>
                                        {% else %}
                                            <a title="Activate Contact" href="{% url 'contact-status-change' 'activate' contact.id %}" class="btn btn-sm btn-success" style="padding:5px 5px;">
                                                <i class="material-icons">check</i>
                                            </a>
                                        {% endif %}
                                        <a title="Delete Contact" href="{% url 'contact-delete' contact.id %}" class="btn btn-danger btn-sm" style="padding:5px 5px;">
                                            <i class="material-icons">delete_forever</i>
                                        </a>
                                        <a title="View Collection For Contact" href="{% url 'contact-collections' contact.id %}" class="btn btn-warning btn-sm" style="padding:5px 5px;">
                                            <i class="material-icons">attach_money</i>
                                        </a>                                        
                                    </td>   
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>    
                </div>
            </div>
        </div>    
    </div>     
</div>