MyAccountBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from app.views import dashboard, contacts, base, invoice, collections, \
    products, inventory, common_views, bundle_pack


# Authorization
urlpatterns = [
    path('', dashboard.index, name = 'home'),
    path('login/', auth_views.LoginView.as_view(template_name = 'app/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'app/registration/logout.html'), name = 'logout'),
    re_path(r'^accounts/*', RedirectView.as_view(pattern_name='login', permanent=True)),
    path('unauthorized/', login_required(base.UnAuthorized.as_view()), name = 'unauthorized'),
]

# Dashboard
urlpatterns += [
    path('dashboard/', never_cache(login_required(dashboard.Dashboard.as_view())), name = 'dashboard'),
]

# Contacts
urlpatterns += [
    path('contacts/', never_cache(login_required(contacts.ContactsView.as_view())), name = 'contacts'),
    path('contacts/add/', never_cache(login_required(contacts.add_contacts)), name = 'add-contacts'),
    path('contacts/add_address/', never_cache(login_required(contacts.add_address_details_form)), name = 'add_address_details_form'),
    path('contacts/add_accounts/', never_cache(login_required(contacts.add_accounts_details_form)), name = 'add_accounts_details_form'),
    path('contacts/edit/<int:ins>/', never_cache(login_required(contacts.edit_contact)), name = 'edit-contact'),
    
    path('contacts/check_appid/', never_cache(login_required(contacts.check_app_id)), name='check-appid'),
    path('contacts/user_exists_in_list/', never_cache(login_required(contacts.user_exists_in_list)), name='check-appid-user-exist'),
    path('contacts/upload/', never_cache(login_required(contacts.ContactsFileUploadView.as_view())), name='contacts-upload'),
    path('contacts/status_change/<slug:slug>/<int:ins>/', never_cache(login_required(contacts.status_change)), name='contact-status-change'),
    path('contacts/delete/<int:ins>/', never_cache(login_required(contacts.delete_contact)), name='contact-delete'),

    path('contacts/edit_contact_details_form/', never_cache(login_required(contacts.edit_contact_details_form)), name = 'edit_contact_details_form'),
    path('contacts/edit_tax_details_form/', never_cache(login_required(contacts.edit_tax_details_form)), name = 'edit_tax_details_form'),
    path('contacts/edit_other_details_form/', never_cache(login_required(contacts.edit_other_details_form)), name = 'edit_other_details_form'),
    path('contacts/edit_address_details_form/', never_cache(login_required(contacts.edit_address_details_form)), name = 'edit_address_details_form'),
    path('contacts/edit_accounts_details_form/', never_cache(login_required(contacts.edit_accounts_details_form)), name = 'edit_accounts_details_form'),
    path('contacts/edit_social_details_form/', never_cache(login_required(contacts.edit_social_details_form)), name = 'edit_social_details_form'),

    path('contacts/delete_address/<int:ins>/', never_cache(login_required(contacts.delete_contact_address)), name = 'delete_contact_address'),
    path('contacts/delete_accounts/<int:ins>/', never_cache(login_required(contacts.delete_accounts_details)), name = 'delete_accounts_details'),

]

# Invoice
urlpatterns += [
    path('invoice/', never_cache(login_required(invoice.Invoice.as_view())), name = 'invoice'),
    path('invoice/invoice_designer/', never_cache(login_required(invoice.InvoiceDesigner.as_view())), name = 'invoice-designer'),
    path('invoice/invoice_designer/manage/', never_cache(login_required(invoice.manage_invoice_designs)), name = 'manage-invoice-designs'),
    path('invoice/create_invoice/', never_cache(login_required(invoice.CreateInvoice.as_view())), name = 'create-invoice'),
    path('invoice/view_invoice/<int:ins>/', never_cache(login_required(invoice.ViewInvoice.as_view())), name = 'view-invoice'),
    path('invoice/create_invoice/contacts/<int:ins>/', never_cache(login_required(invoice.CreateContactInvoice.as_view())), name = 'create-contact-invoice'),
    path('invoice/create_invoice/collections/<int:ins>/', never_cache(login_required(invoice.CreateCollectionInvoice.as_view())), name = 'create-collection-invoice'),
]

urlpatterns +=[
    path('invoice/get_pdf/<int:ins>/', never_cache(login_required(invoice.get_pdf)), name = 'get_pdf'),
    
] 

# Collections
urlpatterns += [
    path('collections/', never_cache(login_required(collections.view_collections)), name = 'collections'),
    path('collections/contact/<int:ins>/', never_cache(login_required(collections.view_contact_collections)), name = 'contact-collections'),
    path('collections/add_collections/', never_cache(login_required(collections.AddCollections.as_view())), name = 'add-collections'),
    path('collections/add_collections/partial/<int:ins>/', never_cache(login_required(collections.AddPartialCollection.as_view())), name = 'add-partial-collections'),
    path('collections/edit/<int:ins>/', never_cache(login_required(collections.Edit_Collection.as_view())), name = 'edit_collections'),
    path('collections/edit_partial/<int:ins>/<int:obj>/', never_cache(login_required(collections.Edit_PartialCollection.as_view())), name = 'edit_partial_collection'),
]

# Products
urlpatterns += [
    path('products/', never_cache(login_required(products.view_products)), name = 'view_products'),
    path('products/add/', never_cache(login_required(products.AddProducts.as_view())), name = 'add_products'),
    path('products/edit/<int:ins>/', never_cache(login_required(products.EditProducts.as_view())), name = 'edit_product'),
    path('products/delete/<int:ins>/', never_cache(login_required(products.delete_product)), name='product-delete'),
    path('products/clone/<int:ins>/', never_cache(login_required(products.clone_product)), name='product-clone'),
    path('products/status_change/<slug:slug>/<int:ins>/', never_cache(login_required(products.status_change)), name='product-status-change'),
]

# Product Bundle
urlpatterns +=[
    path('products/bundle/view/', never_cache(login_required(bundle_pack.ProductBundelView.as_view())), name = 'view_product_bundles'),
]



# Inventory
urlpatterns += [
    path('inventory/', never_cache(login_required(inventory.view_inventory)), name = 'view_inventory'),
    path('inventory/add/', never_cache(login_required(inventory.AddInventory.as_view())), name = 'add_inventory'),
    path('inventory/products/<int:ins>/', never_cache(login_required(inventory.InventoryProducts.as_view())), name = 'view_inventory_products'),
    path('inventory/products/delete/<int:ins>/', never_cache(login_required(inventory.delete_inventory_product)), name = 'delete_inventory_product'),
    path('inventory/get_edit_inventory_product_form/', never_cache(login_required(inventory.get_edit_inventory_product_form)), name = 'get_edit_inventory_product_form'),
    path('inventory/edit_inventory_product/', never_cache(login_required(inventory.edit_inventory_product)), name = 'edit_inventory_product'),
]

# AJAX
urlpatterns += [
    path('fetch_contact_addresses/<int:ins>/', never_cache(login_required(common_views.fetch_contact_addresses)), name='fetch_contact_addresses'),
    path('fetch_product_details/<int:ins>/', never_cache(login_required(common_views.fetch_product_details)), name='fetch_product_details'),
    path('ajax_add_product/', never_cache(login_required(products.ajax_add_product)), name='ajax_add_product'),
    path('fetch_products_dropdown/', never_cache(login_required(common_views.fetch_products_dropdown)), name='fetch_products_dropdown'),
    path('add_contact_or_employee/', never_cache(login_required(common_views.add_contact_or_employee)), name='add_contact_or_employee'),
    path('get_contacts_dropdown/', never_cache(login_required(common_views.get_contacts_dropdown)), name='get_contacts_dropdown'),
    path('add_edit_address/<int:ins>/', never_cache(login_required(common_views.add_edit_address)), name='add_edit_address'),
    path('add_edit_address/<int:ins>/<int:obj>/', never_cache(login_required(common_views.add_edit_address)), name='add_edit_address'),
]





#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

app/models/collects_model.py
from django.db import models
from django.contrib.auth.models import User
from app.models.contacts_model import Contacts
from app.other_constants import *
  
#=====================================================================
# MULTIPLE COLLECTION METHODS
#=====================================================================
class Collections(models.Model):

    user = models.ForeignKey(
        User,
        on_delete = models.SET_NULL,
        db_index = True,
        blank = True,
        null = True,
    )

    contact = models.ForeignKey(
        Contacts,
        on_delete = models.SET_NULL,
        db_index = True,
        blank = True,
        null = True,
    )

    collection_due_date = models.DateTimeField(
        null = True,
        blank = True,
        db_index = True,
    )

    amount = models.FloatField(
        blank = True,
        null = True,
        db_index = True,
    )

    currency_type = models.CharField(
        max_length = 5,
        db_index = True,
        choices = currency_list.CURRENCY_CHOICES,
    )

    payment_type = models.IntegerField(
        default = 1,
        db_index = True,
        choices = payment_constants.PAYMENT_TYPE,
    )

    collection_status = models.IntegerField(
        default = 1,
        db_index = True,
        choices = payment_constants.COLLECTION_STATUS,
    )

    collection_date = models.DateTimeField(
        null = True,
        blank = True,
        db_index = True,
    )

    created_on = models.DateTimeField(
        db_index = True,
        auto_now_add = True,
        auto_now = False,
    )

    def __str__(self):
        if self.contact is not None:
            return self.contact.contact_name
        else:
            return 'Contact Deleted'
#===================================================================================
#   COLLECT PARTIAL MODEL
#===================================================================================
#
class CollectPartial(models.Model):
    
    user = models.ForeignKey(
        User,
        on_delete = models.SET_NULL,
        db_index = True,
        blank = True,
        null = True,
    )

    collect_part = models.ForeignKey(
        Collections,
        on_delete = models.CASCADE,
        db_index = True,
        null = True,
        blank = True,
    )

    collection_due_date = models.DateTimeField(
        null = True,
        blank = True,
        db_index = True,
    )

    amount = models.FloatField(
        blank = True,
        null = True,
        db_index = True,
    )

    currency_type = models.CharField(
        max_length = 5,
        db_index = True,
        choices = currency_list.CURRENCY_CHOICES,
    )

    payment_type = models.IntegerField(
        default = 1,
        db_index = True,
        choices = payment_constants.PAYMENT_TYPE,
    )

    collection_status = models.IntegerField(
        default = 1,
        db_index = True,
        choices = payment_constants.PARTIAL_COLLECTION_STATUS,
    )

    collection_date = models.DateTimeField(
        null = True,
        blank = True,
        db_index = True,
    )

    created_on = models.DateTimeField(
        db_index = True,
        auto_now_add = True,
        auto_now = False,
    )
    

app/forms/collection_forms.py
from django.forms import *
from app.models.collects_model import *
from app.models.contacts_model import *
from django.contrib.auth.models import User

from app.other_constants import *

class CollectionsForm(ModelForm):

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(CollectionsForm, self).__init__(*args, **kwargs)
        self.fields['contact'].queryset = Contacts.objects.filter(user = self.user)

    class Meta:

        model = Collections
        fields = (
                    'contact', 'collection_due_date', 'amount', 'payment_type',
                    'collection_status', 'collection_date', 'currency_type',
                )

        widgets = {
            'contact' : Select(attrs={'class':'form-control input-sm'}),
            'collection_due_date' : DateInput(attrs={'class':'form-control input-sm', 'data-toggle':'datepicker'}),
            'amount' : NumberInput(attrs={'class':'form-control input-sm'}),
            'payment_type' : Select(attrs={'class':'form-control input-sm'}, choices = payment_constants.PAYMENT_TYPE),
            'collection_status' : Select(attrs={'class':'form-control input-sm'}, choices = payment_constants.COLLECTION_STATUS),
            'currency_type' : Select(attrs={'class':'form-control input-sm'}, choices = currency_list.CURRENCY_CHOICES),
            'collection_date' : DateInput(attrs={'class':'form-control input-sm','data-toggle':'datepicker'}),
        }

class CollectPartialForm(ModelForm):
    class Meta:

        model = CollectPartial
        fields = (
                    'collection_due_date', 'amount', 'payment_type',
                    'collection_status', 'collection_date', 'currency_type',
                )

        widgets = {
            'collection_due_date' : DateInput(attrs={'class':'form-control input-sm', 'data-toggle':'datepicker'}),
            'amount' : NumberInput(attrs={'class':'form-control input-sm'}),
            'payment_type' : Select(attrs={'class':'form-control input-sm'}, choices = payment_constants.PAYMENT_TYPE),
            'collection_status' : Select(attrs={'class':'form-control input-sm'}, choices = payment_constants.PARTIAL_COLLECTION_STATUS),
            'collection_date' : DateInput(attrs={'class':'form-control input-sm','data-toggle':'datepicker'}),
            'currency_type' : Select(attrs={'class':'form-control input-sm'}, choices = currency_list.CURRENCY_CHOICES),
        }

app/templates/app/app_files/collections/add_collections_partial.html
{% load common_components %}
{% loader_component %}

<div class="row">
    <div class="col-lg-12" style="padding:0px">
        <div class="card">              
            <div class="card-header">
                <h4>ADD PARTIAL COLLECTION LIST     
                    {% if record.collection_status < 3 %}           
                    <button class="btn button button-green pull-right" data-toggle="modal" data-target="#add_partial">New Entry</button>
                    {% endif %}
                    <a href="{% url 'create-collection-invoice' record.id %}" class="btn button button-black" style="float:right; color:#FFFFFF; margin-right:10px">Create Invoice</a>
                </h4>   
            </div>
            <div class="card-body">
                <div class="table">
                    <table class="table-bordered" width="100%" cellspacing="0" style="color:#000000">
                        <thead style="background-color: #EEEEEE; color:#000000; font-size:11px">
                            <th style="padding: 10px;" class="text-center">UID</th>
                            <th style="padding: 10px;" class="text-center">Contact Name</th>
                            <th style="padding: 10px;" class="text-center">Total Amount</th>
                            <th style="padding: 10px;" class="text-center">Currecy Type</th>
                            <th style="padding: 10px;" class="text-center">Payment Type</th>
                            <th style="padding: 10px;" class="text-center">Status</th>
                            <th style="padding: 10px;" class="text-center">Due Date</th>
                            <th style="padding: 10px;" class="text-center">Collected On Date</th>
                            <th style="padding: 10px;" class="text-center">Created On Date</th>               
                            <th style="padding: 10px;" class="text-center">Action</th>                
                        </thead>
                        <tbody>                            
                            <tr
                                {% if record.collection_status == 1 %}
                                    style="background-color:#ffa50069"
                                {% elif record.collection_status == 2 %}   
                                    style="background-color:rgba(125, 205, 241, 0.5)"
                                {% else %} 
                                    style="background-color:rgba(12, 235, 19, 0.5)"
                                {% endif %}
                            >
                                <td>C-0000{{record.id}}</td>
                                <td>{{record.contact.contact_name}}</td>
                                <td>{{record.amount|safe}}</td>
                                <td>{{record.get_currency_type_display|safe}}</td>
                                <td>{{record.get_payment_type_display|upper}}</td>
                                <td>{{record.get_collection_status_display|upper}}</td>
                                <td>{{record.collection_due_date}}</td>
                                <td>{{record.collection_date}}</td>
                                <td>{{record.created_on}}</td>                      
                                <td>
                                    <a href="{% url 'edit_collections' record.id %}" class="btn btn-primary btn-sm" title="Edit Collection">
                                        <i class="fas fas-fw fa-pencil-alt"></i>
                                    </a>
                                </td>                 
                            </tr>
                        </tbody>
                    </table>
                </div>
                {% if partial_collections.count > 0 %}
                <div class="table" style="padding:10px;">
                    <h5>PARTIAL COLLECTIONS</h5>
                    <table class="table-bordered" width="100%" cellspacing="0" style="color:#000000">
                        <thead style="background-color: #535353; color:#FFFFFF; font-size:11px">
                            <th style="padding: 10px;" class="text-center">UID</th>
                            <th style="padding: 10px;" class="text-center">Amount</th>
                            <th class="text-center">Currency Type</th>
                            <th class="text-center">Payment Type</th>
                            <th class="text-center">Status</th>
                            <th class="text-center">Due Date</th>
                            <th class="text-center">Collected On Date</th>
                            <th class="text-center">Created On Date</th>               
                            <th class="text-center">Action</th>                
                        </thead>
                        <tbody>    
                            {% for p_record in partial_collections %}
                                <tr
                                    {% if p_record.collection_status == 1 %}
                                        style="background-color:#ffa50069"
                                    {% elif p_record.collection_status == 2 %}    
                                        style="background-color:rgba(125, 205, 241, 0.5)"
                                    {% else %}
                                        style="background-color:rgba(12, 235, 19, 0.5)"
                                    {% endif %}
                                >
                                    <td>P-0000{{p_record.id|safe}}</td>
                                    <td>{{p_record.amount|safe}}</td>
                                    <td>{{p_record.get_currency_type_display|safe}}</td>
                                    <td>{{p_record.get_payment_type_display|upper}}</td>
                                    <td>{{p_record.get_collection_status_display|upper}}</td>
                                    <td>{{p_record.collection_due_date}}</td>
                                    <td>{{p_record.collection_date}}</td>
                                    <td>{{p_record.created_on}}</td>                      
                                    <td>
                                        <a href="{% url 'edit_partial_collection' record.id p_record.id %}" class="btn btn-primary btn-sm" title="Edit Collection">
                                            <i class="fas fas-fw fa-pencil-alt"></i>
                                        </a>
                                    </td>                 
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class="table" style="padding:10px;">
                        <table class="table-responsive">
                            <tr>
                                <td> Balance Amount</td>
                                <td width="100px">{{balance_amount}}</td>
                            </tr>
                        </table>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="modal" id="add_partial" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="post">
                <div class="modal-header">
                    <h5 class="modal-title">Add Partial Collection</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="table" style="padding:10px 0px;">
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:5px 10px;">
                                <label>Amount</label>
                            </div>
                            <div class="d-table-cell" style="padding:0px 13px;">
                                {{collection_form.amount}}
                            </div>                        
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:5px 10px;">
                                <label>Currency Type</label>
                            </div>
                            <div class="d-table-cell" style="padding:0px 13px;">
                                {{collection_form.currency_type}}
                            </div>                        
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:5px 10px;">
                                <label>Due Date</label>
                            </div>
                            <div class="d-table-cell" style="padding:0px 13px;">
                                {{collection_form.collection_due_date}}
                            </div>                        
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:5px 10px;">
                                <label>Mode Of Payment</label>
                            </div>
                            <div class="d-table-cell" style="padding:0px 13px;">
                                {{collection_form.payment_type}}
                            </div>                        
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:5px 10px;">
                                <label>Status</label>
                            </div>
                            <div class="d-table-cell" style="padding:0px 13px;">
                                {{collection_form.collection_status}}
                            </div>                        
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:5px 10px;">
                                <label>Collection Date</label>
                            </div>
                            <div class="d-table-cell" style="padding:0px 13px;">
                                {{collection_form.collection_date}}
                            </div>                        
                        </div>
                    </div>      
                </div>
                <div class="modal-footer">
                    <button class="btn button button-green">Save changes</button>
                    <button type="button" class="btn button-orange" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
  </div>

app/templates/app/app_files/collections/index.html
{% extends 'app/base/base.html' %}
{% load static %}

{% load common_filters %}
{% load pagination %}

{% block content %}

<div class="row custom-row" style="padding:10px;background-color: #000000; background-size: cover;">
    <ul style="list-style:none; margin:0px; color:#FFFFFF;">
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'collections' %}" style="color:#FFFFFF; text-decoration:none;" title="View Collections">
                <i class="fas fw fa-th-list"></i>
            </a>
        </li>
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'add-collections' %}" style="color:#FFFFFF; text-decoration:none;" title="Add Collection">
                <i class="fas fa-fw fa-plus-square"></i>
            </a>
        </li>        
    </ul>
</div>

<div class="container">
    {% include included_template %}
</div>


{% endblock %}

app/templates/app/app_files/collections/view_collections.html
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="table">
                    <table class="table-bordered" width="100%" cellspacing="0" style="color:#000000">
                        <thead  style="background-color: #EEEEEE; color:#000000; font-size:11px">
                            <th>UID</th>
                            <th class="text-center">Contact Name</th>
                            <th class="text-center">Amount</th>
                            <th class="text-center">Currency Type</th>
                            <th class="text-center">Payment Type</th>
                            <th class="text-center">Status</th>
                            <th class="text-center">Due Date</th>
                            <th class="text-center">Collected On Date</th>
                            <th class="text-center">Created On Date</th>               
                            <th class="text-center">Action</th>                
                        </thead>
                        <tbody>
                            {% for record in collections %}
                                <tr
                                    {% if record.collection_status == 1 %}
                                        style="background-color:#ffa50069"
                                    {% elif record.collection_status == 2 %}    
                                        style="background-color:rgba(125, 205, 241, 0.5)"
                                    {% else %}
                                        style="background-color:rgba(12, 235, 19, 0.5)"
                                    {% endif %}
                                >
                                    <td>C-0000{{record.id}}</td>
                                    <td>{{record.contact.contact_name}}</td>
                                    <td>{{record.amount|safe}}</td>
                                    <td>{{record.get_currency_type_display|safe}}</td>
                                    <td>{{record.get_payment_type_display|upper}}</td>
                                    <td>{{record.get_collection_status_display|upper}}</td>
                                    <td>{{record.collection_due_date}}</td>
                                    <td>{{record.collection_date}}</td>
                                    <td>{{record.created_on}}</td>                      
                                    <td>
                                        <a href="{% url 'edit_collections' record.id %}" class="btn btn-primary btn-sm" title="Edit Collection">
                                            <i class="fas fas-fw fa-pencil-alt"></i>
                                        </a>                                        
                                        <a href="{% url 'add-partial-collections' record.id %}" class="btn button-orange btn-sm" title="Add Partial Collection">
                                            <i class="fas fas-fw fa-hand-holding-usd"></i>
                                        </a>
                                        {% if record.collection_status == 3 %}
                                        <a href="{% url 'create-collection-invoice' record.id %}" class="btn button-black btn-sm" title="Create Invoice">
                                            <i style="color:#FFFFFF" class="fas fas-fw fa-file-invoice"></i style="color:#FFFFFF">
                                        </a>
                                        {% endif %}
                                    </td>                 
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>