MyAccountBook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from app.views import dashboard, contacts, base, invoice, collections, \
    products, inventory, common_views, bundle_pack


# Authorization
urlpatterns = [
    path('', dashboard.index, name = 'home'),
    path('login/', auth_views.LoginView.as_view(template_name = 'app/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'app/registration/logout.html'), name = 'logout'),
    re_path(r'^accounts/*', RedirectView.as_view(pattern_name='login', permanent=True)),
    path('unauthorized/', login_required(base.UnAuthorized.as_view()), name = 'unauthorized'),
]

# Dashboard
urlpatterns += [
    path('dashboard/', never_cache(login_required(dashboard.Dashboard.as_view())), name = 'dashboard'),
]

# Contacts
urlpatterns += [
    path('contacts/', never_cache(login_required(contacts.ContactsView.as_view())), name = 'contacts'),
    path('contacts/add/', never_cache(login_required(contacts.add_contacts)), name = 'add-contacts'),
    path('contacts/add_address/', never_cache(login_required(contacts.add_address_details_form)), name = 'add_address_details_form'),
    path('contacts/add_accounts/', never_cache(login_required(contacts.add_accounts_details_form)), name = 'add_accounts_details_form'),
    path('contacts/edit/<int:ins>/', never_cache(login_required(contacts.edit_contact)), name = 'edit-contact'),
    
    path('contacts/check_appid/', never_cache(login_required(contacts.check_app_id)), name='check-appid'),
    path('contacts/user_exists_in_list/', never_cache(login_required(contacts.user_exists_in_list)), name='check-appid-user-exist'),
    path('contacts/upload/', never_cache(login_required(contacts.ContactsFileUploadView.as_view())), name='contacts-upload'),
    path('contacts/status_change/<slug:slug>/<int:ins>/', never_cache(login_required(contacts.status_change)), name='contact-status-change'),
    path('contacts/delete/<int:ins>/', never_cache(login_required(contacts.delete_contact)), name='contact-delete'),

    path('contacts/edit_contact_details_form/', never_cache(login_required(contacts.edit_contact_details_form)), name = 'edit_contact_details_form'),
    path('contacts/edit_tax_details_form/', never_cache(login_required(contacts.edit_tax_details_form)), name = 'edit_tax_details_form'),
    path('contacts/edit_other_details_form/', never_cache(login_required(contacts.edit_other_details_form)), name = 'edit_other_details_form'),
    path('contacts/edit_address_details_form/', never_cache(login_required(contacts.edit_address_details_form)), name = 'edit_address_details_form'),
    path('contacts/edit_accounts_details_form/', never_cache(login_required(contacts.edit_accounts_details_form)), name = 'edit_accounts_details_form'),
    path('contacts/edit_social_details_form/', never_cache(login_required(contacts.edit_social_details_form)), name = 'edit_social_details_form'),

    path('contacts/delete_address/<int:ins>/', never_cache(login_required(contacts.delete_contact_address)), name = 'delete_contact_address'),
    path('contacts/delete_accounts/<int:ins>/', never_cache(login_required(contacts.delete_accounts_details)), name = 'delete_accounts_details'),

]

# Invoice
urlpatterns += [
    path('invoice/', never_cache(login_required(invoice.Invoice.as_view())), name = 'invoice'),
    path('invoice/invoice_designer/', never_cache(login_required(invoice.InvoiceDesigner.as_view())), name = 'invoice-designer'),
    path('invoice/invoice_designer/manage/', never_cache(login_required(invoice.manage_invoice_designs)), name = 'manage-invoice-designs'),
    path('invoice/create_invoice/', never_cache(login_required(invoice.CreateInvoice.as_view())), name = 'create-invoice'),
    path('invoice/view_invoice/<int:ins>/', never_cache(login_required(invoice.ViewInvoice.as_view())), name = 'view-invoice'),
    path('invoice/create_invoice/contacts/<int:ins>/', never_cache(login_required(invoice.CreateContactInvoice.as_view())), name = 'create-contact-invoice'),
    path('invoice/create_invoice/collections/<int:ins>/', never_cache(login_required(invoice.CreateCollectionInvoice.as_view())), name = 'create-collection-invoice'),
]

urlpatterns +=[
    path('invoice/get_pdf/<int:ins>/', never_cache(login_required(invoice.get_pdf)), name = 'get_pdf'),
    
] 

# Collections
urlpatterns += [
    path('collections/', never_cache(login_required(collections.view_collections)), name = 'collections'),
    path('collections/contact/<int:ins>/', never_cache(login_required(collections.view_contact_collections)), name = 'contact-collections'),
    path('collections/add_collections/', never_cache(login_required(collections.AddCollections.as_view())), name = 'add-collections'),
    path('collections/add_collections/partial/<int:ins>/', never_cache(login_required(collections.AddPartialCollection.as_view())), name = 'add-partial-collections'),
    path('collections/edit/<int:ins>/', never_cache(login_required(collections.Edit_Collection.as_view())), name = 'edit_collections'),
    path('collections/edit_partial/<int:ins>/<int:obj>/', never_cache(login_required(collections.Edit_PartialCollection.as_view())), name = 'edit_partial_collection'),
]

# Products
urlpatterns += [
    path('products/', never_cache(login_required(products.view_products)), name = 'view_products'),
    path('products/add/', never_cache(login_required(products.AddProducts.as_view())), name = 'add_products'),
    path('products/edit/<int:ins>/', never_cache(login_required(products.EditProducts.as_view())), name = 'edit_product'),
    path('products/delete/<int:ins>/', never_cache(login_required(products.delete_product)), name='product-delete'),
    path('products/clone/<int:ins>/', never_cache(login_required(products.clone_product)), name='product-clone'),
    path('products/status_change/<slug:slug>/<int:ins>/', never_cache(login_required(products.status_change)), name='product-status-change'),
]

# Product Bundle
urlpatterns +=[
    path('products/bundle/view/', never_cache(login_required(bundle_pack.ProductBundelView.as_view())), name = 'view_product_bundles'),
]



# Inventory
urlpatterns += [
    path('inventory/', never_cache(login_required(inventory.view_inventory)), name = 'view_inventory'),
    path('inventory/add/', never_cache(login_required(inventory.AddInventory.as_view())), name = 'add_inventory'),
    path('inventory/products/<int:ins>/', never_cache(login_required(inventory.InventoryProducts.as_view())), name = 'view_inventory_products'),
    path('inventory/products/delete/<int:ins>/', never_cache(login_required(inventory.delete_inventory_product)), name = 'delete_inventory_product'),
    path('inventory/get_edit_inventory_product_form/', never_cache(login_required(inventory.get_edit_inventory_product_form)), name = 'get_edit_inventory_product_form'),
    path('inventory/edit_inventory_product/', never_cache(login_required(inventory.edit_inventory_product)), name = 'edit_inventory_product'),
]

# AJAX
urlpatterns += [
    path('fetch_contact_addresses/<int:ins>/', never_cache(login_required(common_views.fetch_contact_addresses)), name='fetch_contact_addresses'),
    path('fetch_product_details/<int:ins>/', never_cache(login_required(common_views.fetch_product_details)), name='fetch_product_details'),
    path('ajax_add_product/', never_cache(login_required(products.ajax_add_product)), name='ajax_add_product'),
    path('fetch_products_dropdown/', never_cache(login_required(common_views.fetch_products_dropdown)), name='fetch_products_dropdown'),
    path('add_contact_or_employee/', never_cache(login_required(common_views.add_contact_or_employee)), name='add_contact_or_employee'),
    path('get_contacts_dropdown/', never_cache(login_required(common_views.get_contacts_dropdown)), name='get_contacts_dropdown'),
    path('add_edit_address/<int:ins>/', never_cache(login_required(common_views.add_edit_address)), name='add_edit_address'),
    path('add_edit_address/<int:ins>/<int:obj>/', never_cache(login_required(common_views.add_edit_address)), name='add_edit_address'),
]





#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

app/models/invoice_model.py
from django.db import models
from django.contrib.auth.models import User
from app.models.contacts_model import *
from app.models.collects_model import *
from app.models.users_model import *
from app.models.items_model import *

from uuid import uuid4
import os

#==========================================================================
#   CHANGE LOGO FILE NAMES
#==========================================================================
#
def logo_rename(instance, filename):

    upload_path = 'logos'
    ext = filename.split('.')[-1]
    return  os.path.join(upload_path,'{}.{}'.format(uuid4().hex, ext))

#==========================================================================
#   CHANGE ATTACHMENT FILE NAMES
#==========================================================================
#
def attachment_file_rename(instance, filename):

    upload_path = 'invoice_attachments'
    ext = filename.split('.')[-1]
    return  os.path.join(upload_path,'{}.{}'.format(uuid4().hex, ext))


#==========================================================================
#   USER INVOICE DESIGN MODEL
#==========================================================================
#
class Invoice_Templates(models.Model):

    DESIGN_STYLES = (
        (1, 'GREEN TEMPLATE'),
        (2, 'ORANGE TEMPLATE'),
        (3, 'BLUE TEMPLATE'),
        (4, 'WHITE TEMPLATE'),
        (5, 'GREY TEMPLATE'),
        (6, 'CUSTOM TEMPLATE')
    )

    IS_ACTIVE = ((True, 'YES'), (False, 'NO'))

    USER_NAME_ON_TEMPLATE = (
        (True, 'USE USER FIRSTNAME LASTNAME'),
        (False,'USE CUSTOM USERNAME'),
    )

    user = models.ForeignKey(
        User, 
        db_index = True, 
        on_delete = models.CASCADE,
        null = True,
        blank = True,
    )

    template_name = models.CharField(
        max_length = 250,
        db_index = True,
        null = False,
        blank = False,
    )

    design_number = models.IntegerField(        
        db_index = True,
        default = 1,
        choices = DESIGN_STYLES,
    )

    logo = models.FileField(
        null = True,
        blank = True,
        upload_to = logo_rename,
    )

    header_bgcolor = models.CharField(
        max_length = 20,
        null = True,
        blank = True,
        default = "#FFFFFF",
    )

    header_fgcolor = models.CharField(
        max_length = 20,
        null = True,
        blank = True,
        default = "#000000",
    )

    other_design_colors = models.CharField(
        max_length = 20,
        blank =  True,
        null = True,
        default = "#FFFFFF",
    )

    is_active = models.BooleanField(
        db_index = True,
        choices =  IS_ACTIVE,
        default = True,
    )

    user_display_name = models.BooleanField(
        db_index = True,
        choices = USER_NAME_ON_TEMPLATE,
        default = True,
    )

    user_custom_name = models.CharField(
        max_length = 250,
        blank = True,
        null = True,
    )

    user_phone = models.CharField(
        max_length = 30,
        blank = True,
        null = True,
    )

    user_email = models.CharField(
        max_length = 250,
        blank = True,
        null = True,
    )

    billing_address = models.ForeignKey(
        User_Address_Details,
        blank = True,
        null = True,
        db_index = True,
        on_delete = models.SET_NULL,
    )

    total_usage = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )

    created_on = models.DateTimeField(
        auto_now = True,
        db_index = True,
    )

    def __str__(self):
        return self.template_name.upper() 


#==========================================================================
#   INVOICE MODEL
#==========================================================================

class InvoiceModel(models.Model):

    invoice_template = models.ForeignKey(
        Invoice_Templates,
        db_index = True,
        null = True,
        blank = True,
        on_delete = models.SET_NULL,
    )

    service_provider = models.ForeignKey(
        User, 
        on_delete = models.SET_NULL, 
        null = True,
        blank = True,
        db_index = True,
    )

    service_recipient = models.ForeignKey(
        Contacts, 
        on_delete = models.SET_NULL, 
        db_index = True,
        null = True,
        blank = True,
    )

    service_recipient_address = models.IntegerField(
        null = True,
        blank = True,
        db_index = True,
    )


    invoice_no = models.CharField(
        max_length = 20,
        db_index = True,
        blank = True,
        null = True,
    )

    invoice_type = models.BooleanField(
        default = False,
        db_index = True,
        blank = True,
        null = True,
        choices = items_constant.INVOICE_TYPE
    )

    provider_state_code = models.CharField(
        max_length = 10,
        null = True,
        blank = True,
        db_index = True,
    ) 

    recipient_state_code = models.CharField(
        max_length = 10,
        null = True,
        blank = True,
        db_index = True,
    ) 

    sac_code = models.CharField(
        max_length = 20,
        null = True,
        blank = True,
        db_index = True,
    ) 

    service_description = models.TextField(
        blank = True,
        null = True,
    )

    collect = models.ForeignKey(
        Collections,
        db_index = True,
        blank = True,
        null = True,
        on_delete = models.CASCADE,
    ) 

    cgst = models.FloatField(
        default = 0,
        db_index = True,
    )

    igst = models.FloatField(
        default = 0,
        db_index = True,
    )

    sgst = models.FloatField(
        default = 0,
        db_index = True,
    )

    total_gst = models.FloatField(
        default = 0,
        db_index = True,
    )

    adjustment = models.FloatField(
        default = 0,
        db_index = True,
    )

    shipping = models.FloatField(
        default = 0,
        db_index = True,
    )

    discount = models.FloatField(
        default = 0,
        db_index = True,
    )

    sales_person = models.ForeignKey(
        Contacts,
        on_delete = models.SET_NULL,
        blank = True,
        null = True,
        related_name = 'sales_person'
    )

    due_date = models.DateField(
        null = True,
        blank = True,
        db_index = True,
    )

    terms_invoice = models.CharField(
        blank = True,
        max_length = 50,
        null = True,
    )

    message = models.TextField(
        null = True,
        blank = True,
    )

    attachments = models.FileField(
        null = True,
        blank = True,
        upload_to = attachments_rename,
    )

    created_on = models.DateTimeField(
        auto_now = True,
        db_index = True,
    )

    start_date = models.DateField(
        null = True,
        blank = True,
        db_index = True,
    )

    frequency = models.IntegerField(
        null = True,
        blank = True,
        choices = items_constant.INVOICE_FREQUENCY
    )

    repeat_for = models.IntegerField(
        null = True,
        blank = True,
        db_index = True,
    )

    subtotal = models.FloatField(
        default = 0,
        db_index = True,
    )

    subtotal_inc_tax = models.FloatField(
        default = 0,
        db_index = True,
    )

    total = models.FloatField(
        default = 0,
        db_index = True,
    )


    class Meta:
        verbose_name_plural = 'invoice_tbl'


#======================================================================================
# PRODUCTS LISTED IN INVOICE
#======================================================================================
#
class InvoiceProducts(models.Model):

    invoice = models.ForeignKey(
        InvoiceModel,
        db_index = True,
        blank = True,
        null = True,
        on_delete = models.CASCADE,
    )        

    product = models.ForeignKey(
        ProductsModel,
        on_delete = models.SET_NULL,
        db_index = True,
        blank = True,
        null = True,
    )

    inventory = models.ForeignKey(
        InventoryProduct,
        on_delete = models.SET_NULL,
        db_index = True,
        null = True,
        blank = True,
    )

    quantity = models.IntegerField(
        db_index = True,
        null = True,
        blank = True,
    )

    class Meta:
        verbose_name_plural = 'invoice_product_tbl'

app/templates/app/app_files/invoice/create_invoice.html
{% extends 'app/base/base.html' %}
{% load static %}

{% load common_filters %}
{% load pagination %}

{% block content %}

<div class="row custom-row" style="padding:10px;background-color: #000000; background-size: cover; font-weight:bold">
    <ul style="list-style:none; margin:0px; color:#FFFFFF;line-height:40px">
        <li class="nav-item" style="float:left;padding:0px 10px; font-weight:bold">
            <a style="color:#FFFFFF; text-decoration: none;" href="{% url 'invoice' %}" >
                INVOICE <i class="fas fw fa-chevron-circle-right" style="margin-left:10px;"></i>
            </a>
        </li>
        {{breadcrumbs|safe}}
    </ul>
    <a href="?section=all" class="btn button button-orange" style="float:right; position:absolute; right:10px;">Preview</a>
</div>

<div class="container">
    {% include included_template %}
</div>

{% endblock %}

app/templates/app/app_files/invoice/form.html
{% load static %}
<div class="row">
    <div class="col-lg-12" style="padding:0px">
        <div class="card">
            <div class="card-header bg-blue">
                <h5 class="card-title"> 
                        INVOICE CREATION
                    </h5>
                <h6 class="card-subtitle mb-2 text-muted">Add Invoice against a Contact</h6>
            </div>
            <div class="card-header" style="padding:10px 0px; background-color:#ffffff;">
                <h5>Choose Invoice Template</h5>

                <div class="table">
                    <div class="d-table-row" style="padding:10px 0px;">
                        <div class="d-table-cell" style="padding:0px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_1.jpg' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                        <div class="d-table-cell" style="padding:0px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_2.jpg' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                        <div class="d-table-cell" style="padding:10px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_3.png' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                        <div class="d-table-cell" style="padding:10px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_4.jpg' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                        <div class="d-table-cell" style="padding:10px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_5.png' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                        <div class="d-table-cell" style="padding:10px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_6.jpg' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                        <div class="d-table-cell" style="padding:10px 10px;">
                            <img style="width:100px; height:110px; border:1px solid #000000; cursor:pointer;" src="{% static 'invoice_templates/Design_7.png' %}" alt="Invoice Design 1" class="img"/>
                        </div>
                    </div>
                </div>
            </div>
            <form method="post">
                <div class="card-body">
                    {% csrf_token %}
                    <div class="table" style="padding:10px 0px;">
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:0px 10px;">
                                <label>Contact</label>
                            </div>
                            <div class="d-table-cell" style="padding:5px 10px;">
                                {{invoice_form.service_recipient}}
                            </div>
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:0px 10px;">
                                <label>Contact Billing Address</label>
                            </div>
                            <div class="d-table-cell" style="padding:5px 10px;">
                                {{invoice_form.service_recipient}}
                            </div>
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:0px 10px;">
                                <label>Contact Shipping Address</label>
                            </div>
                            <div class="d-table-cell" style="padding:5px 10px;">
                                {{invoice_form.service_recipient}}
                            </div>
                        </div>
                        <div class="d-table-row" style="padding:10px 0px;">
                            <div class="d-table-cell" style="padding:0px 10px;">
                                <label>Contact</label>
                            </div>
                            <div class="d-table-cell" style="padding:5px 10px;">
                                {{invoice_form.service_recipient}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button class="btn button button-green">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/templates/app/app_files/invoice/index.html
{% extends 'app/base/base.html' %}
{% load static %}

{% load common_filters %}
{% load pagination %}

{% block content %}

<div class="row custom-row" style="padding:10px; background: linear-gradient(60deg,#f5700c,#ff9800);">
    <ul style="list-style:none; margin:0px; color:#FFFFFF; padding:0px;">    
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'create-invoice' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Create Invoice">
                <i class="material-icons">bookmarks</i>
            </a>
        </li>  
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'invoice' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Manage Invoices">
                <i class="material-icons">assignment_turned_in</i>
            </a>
        </li>       
        <li class="nav-item" style="float:left;padding:0px 10px;">
            <a href="{% url 'invoice-designer' %}" style="color:#FFFFFF; text-decoration:none; font-size: 20px;" title="Invoice Designer">
                <i class="material-icons">build</i>
            </a>
        </li>        
    </ul>
</div>

<div class="container">
    {% include included_template %}
</div>

{% endblock %}

app/templates/app/app_files/invoice/invoice_template.html
{% load common_components %}
{% loader_component %}

<div class="row">
    <div class="col-lg-12" style="padding:0px">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">Invoice Preview</h4>
            </div> 
            <div class="card-body">
                <div class="table">
                    <table class="table-responsive table-bordered">
                        <tr style="width:100%">
                            <td style="border:0px;">INVOICE No.</td>
                            <td>INV-0000{{invoice_details.id}}</td>
                        </tr>
                        <tr>
                            <td style="border:0px;">CONTACT</td> 
                            <td>
                                {{invoice_details.service_recipient.contact_name|title}}
                            </td>
                        </tr>
                        
                    </table>
                </div>  
            </div>
        </div>
    </div>
</div>                  

app/templates/app/app_files/invoice/manage_invoice_designs.html
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="table">
                    <table class="table-bordered" width="100%" cellspacing="0" style="color:#000000">
                        <thead style="background-color: #EEEEEE; color:#000000; font-size:11px">
                            <th style="padding: 10px;" class="text-center">Template</th>
                            <th style="padding: 10px;" class="text-center">System Provided Design</th>
                            <th style="padding: 10px;" class="text-center">Custom Design</th>
                            <th style="padding: 10px;" class="text-center">Logo</th>
                            <th style="padding: 10px;" class="text-center">Status</th>
                            <th style="padding: 10px;" class="text-center">Used Counter</th>
                            <th style="padding: 10px;" class="text-center">Created On Date</th>               
                            <th style="padding: 10px;" class="text-center">Action</th>                
                        </thead>
                        <tbody>
                            {% for record in designs %}
                                <tr>
                                    <td>{{record.template_name|upper}}</td>
                                    <td class="text-center">
                                        {% if record.design_number <= 5 %}
                                            {{record.get_design_number_display|upper}}
                                        {% else %}
                                            <i class="fa fa-fw fa-times"></i>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if record.design_number == 6 %}
                                            <i class="fa fa-fw fa-check"></i>
                                        {% else %}
                                            <i class="fa fa-fw fa-times"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <img src="/media/{{record.logo}}" style="width:50px; height:auto;" class="img-responsive">
                                    </td>
                                    <td class="text-center">
                                        {% if record.is_active %}
                                            <i class="fa fa-fw fa-check"></i>
                                        {% else %}
                                            <i class="fa fa-fw fa-times"></i>
                                        {% endif %}
                                    </td>
                                    <td>{{record.collection_date}}</td>
                                    <td>{{record.created_on}}</td>                      
                                    <td>
                                        <a href="" class="btn btn-primary btn-sm" title="Edit Invoice Design">
                                            <i class="fas fas-fw fa-pencil-alt"></i>
                                        </a>     
                                        {% if record.is_active %}  
                                            <button class="btn button-orange btn-sm" title="De-Activate Invoice Design">
                                                <i class="fas fas-fw fa-times"></i>
                                            </button>
                                        {% else %}
                                            <button class="btn button-green btn-sm" title="Activate Invoice Design">
                                                <i class="fas fas-fw fa-check"></i>
                                            </button>
                                        {% endif %}
                                        <button class="btn button-red btn-sm" title="Delete Invoice Design">
                                            <i class="fas fas-fw fa-trash-alt"></i>
                                        </button>
                                    </td>                 
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>